src/VentasBundle/Entity/FacturaDetalle.php
<?php

namespace VentasBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * VentasBundle\Entity\FacturaDetalle
 * @ORM\Table(name="ventas_factura_detalle")
 * @ORM\Entity()
 */
class FacturaDetalle {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer $orden
     * @ORM\Column(name="orden", type="integer",nullable=true)
     */
    protected $orden;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Producto")
     * @ORM\JoinColumn(name="producto_id", referencedColumnName="id")
     */
    protected $producto;

    /**
     * @var integer $cantidad
     * @ORM\Column(name="cantidad", type="decimal", precision=20, scale=2)
     */
    protected $cantidad = 1;

    /**
     * @ORM\Column(name="bulto", type="boolean", nullable=true)
     */
    protected $bulto = false;

    /**
     * @var integer $cantidadxBulto
     * @ORM\Column(name="cantidad_x_bulto", type="integer", nullable=true )
     */
    protected $cantidadxBulto;

    /**
     * @var integer $precio
     * @ORM\Column(name="precio", type="decimal", precision=20, scale=2 )
     */
    protected $precio;

    /**
     * @var integer $iva
     * @ORM\Column(name="iva", type="decimal", precision=20, scale=2 )
     */
    protected $iva;

    /**
     * @var integer $descuento
     * @ORM\Column(name="descuento", type="decimal", precision=20, scale=2 )
     */
    protected $descuento = 0;

    /**
     * @ORM\ManyToOne(targetEntity="VentasBundle\Entity\Factura", inversedBy="detalles")
     * @ORM\JoinColumn(name="ventas_factura_id", referencedColumnName="id")
     */
    protected $factura;

    /*
     * DATOS PARA AFIP
     */

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\AfipAlicuota")
     * @ORM\JoinColumn(name="afip_alicuota_id", referencedColumnName="id")
     * */
    protected $afipAlicuota;

    /**
     * Constructor
     */
    public function __construct() {
        //$this->iva = 21;
        $this->descuento = 0;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set orden
     *
     * @param integer $orden
     * @return FacturaDetalle
     */
    public function setOrden($orden) {
        $this->orden = $orden;

        return $this;
    }

    /**
     * Get orden
     *
     * @return integer
     */
    public function getOrden() {
        return $this->orden;
    }

    /**
     * Set cantidad
     *
     * @param integer $cantidad
     * @return FacturaDetalle
     */
    public function setCantidad($cantidad) {
        $this->cantidad = $cantidad;

        return $this;
    }

    /**
     * Get cantidad
     *
     * @return integer
     */
    public function getCantidad() {
        return $this->cantidad;
    }

    /**
     * Set precio
     *
     * @param string $precio
     * @return FacturaDetalle
     */
    public function setPrecio($precio) {
        $this->precio = $precio;

        return $this;
    }

    /**
     * Get precio
     *
     * @return string
     */
    public function getPrecio() {
        return $this->precio;
    }

    /**
     * Set iva
     *
     * @param string $iva
     * @return FacturaDetalle
     */
    public function setIva($iva) {
        $this->iva = $iva;

        return $this;
    }

    /**
     * Get iva
     *
     * @return string
     */
    public function getIva() {
        return $this->iva;
    }

    /**
     * Set descuento
     *
     * @param string $descuento
     * @return FacturaDetalle
     */
    public function setDescuento($descuento) {
        $this->descuento = $descuento;

        return $this;
    }

    /**
     * Get descuento
     *
     * @return string
     */
    public function getDescuento() {
        return $this->descuento;
    }

    /**
     * Set producto
     *
     * @param \AppBundle\Entity\Producto $producto
     * @return FacturaDetalle
     */
    public function setProducto(\AppBundle\Entity\Producto $producto = null) {
        $this->producto = $producto;

        return $this;
    }

    /**
     * Get producto
     *
     * @return \AppBundle\Entity\Producto
     */
    public function getProducto() {
        return $this->producto;
    }

    /**
     * Set factura
     *
     * @param \VentasBundle\Entity\Factura $factura
     * @return FacturaDetalle
     */
    public function setFactura(\VentasBundle\Entity\Factura $factura = null) {
        $this->factura = $factura;

        return $this;
    }

    /**
     * Get factura
     *
     * @return \VentasBundle\Entity\Factura
     */
    public function getFactura() {
        return $this->factura;
    }

    /** Calculos * */
    public function getSubTotal() {
        return $this->precio * $this->cantidad;
    }

    public function getMontoDescuento() {
        return $this->getSubTotal() * ($this->descuento / 100);
    }

    /*   public function getMontoIva(){
      return ( $this->getSubTotal() - $this->getMontoDescuento() ) * ($this->iva/100);
      } */

    public function getTotal() {
        return ($this->getSubTotal() - $this->getMontoDescuento()) + $this->getIva();
    }

    // Cantidad para mostrar como texto
    public function getCantidadTxt() {
        if ($this->bulto) {
            return $this->getCantidad() . ' x ' . $this->getCantidadxBulto() . ' ' . $this->getProducto()->getUnidadMedida()->getNombre();
        }
        else {
            return $this->getCantidad() . ' ' . $this->getProducto()->getUnidadMedida()->getNombre();
        }
    }

    /**
     * Set bulto
     *
     * @param boolean $bulto
     * @return FacturaDetalle
     */
    public function setBulto($bulto) {
        $this->bulto = $bulto;

        return $this;
    }

    /**
     * Get bulto
     *
     * @return boolean
     */
    public function getBulto() {
        return $this->bulto;
    }

    /**
     * Set cantidadxBulto
     *
     * @param string $cantidadxBulto
     * @return FacturaDetalle
     */
    public function setCantidadxBulto($cantidadxBulto) {
        $this->cantidadxBulto = $cantidadxBulto;

        return $this;
    }

    /**
     * Get cantidadxBulto
     *
     * @return string
     */
    public function getCantidadxBulto() {
        return $this->cantidadxBulto;
    }

    /**
     * Set afipAlicuota
     *
     * @param \ConfigBundle\Entity\AfipAlicuota $afipAlicuota
     * @return FacturaDetalle
     */
    public function setAfipAlicuota(\ConfigBundle\Entity\AfipAlicuota $afipAlicuota = null) {
        $this->afipAlicuota = $afipAlicuota;

        return $this;
    }

    /**
     * Get afipAlicuota
     *
     * @return \ConfigBundle\Entity\AfipAlicuota
     */
    public function getAfipAlicuota() {
        return $this->afipAlicuota;
    }

}

src/VentasBundle/Entity/NotaDebCred.php
<?php

namespace VentasBundle\Entity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * VentasBundle\Entity\NotaDebCred
 * @ORM\Table(name="ventas_nota_debcred")
 * @ORM\Entity(repositoryClass="VentasBundle\Entity\NotaDebCredRepository")
 * @Gedmo\Loggable()
 */
class NotaDebCred {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var datetime $fecha
     * @ORM\Column(name="fecha", type="datetime", nullable=false)
     */
    private $fecha;

    /**
     * @var string $estado
     * @ORM\Column(name="estado", type="string")
     * @Gedmo\Versioned()
     */
    protected $estado;

    /**
     * 'CRE' = '-'; 'DEB' = '+'
     * @var string $signo
     * @ORM\Column(name="signo", type="string",length=1)
     * @Gedmo\Versioned()
     */
    protected $signo = '+';

    /**
     * @ORM\OneToOne(targetEntity="VentasBundle\Entity\FacturaElectronica", mappedBy="notaDebCred", cascade={"persist"})
     * @Gedmo\Versioned()
     */
    protected $notaElectronica;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\AfipComprobante")
     * @ORM\JoinColumn(name="afip_comprobante_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     * */
    protected $tipoComprobante;

    /**
     * @var integer $descuentoRecargo
     * @ORM\Column(name="descuentoRecargo", type="decimal", precision=20, scale=2,nullable=true )
     * @Gedmo\Versioned()
     */
    protected $descuentoRecargo = 0;

    /**
     * @var integer $iva
     * @ORM\Column(name="iva", type="decimal", precision=20, scale=2,nullable=true )
     * @Gedmo\Versioned()
     */
    protected $iva;

    /**
     * @var integer $percIibb
     * @ORM\Column(name="perc_iibb", type="decimal", precision=20, scale=2,nullable=true )
     * @Gedmo\Versioned()
     */
    protected $percIibb = 0;

    /**
     * @var integer $total
     * @ORM\Column(name="total", type="decimal", precision=20, scale=2 )
     * @Gedmo\Versioned()
     */
    protected $total;

    /**
     * @var integer $saldo
     * @ORM\Column(name="saldo", type="decimal", precision=20, scale=2,nullable=true )
     * @Gedmo\Versioned()
     */
    protected $saldo = 0;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\FormaPago")
     * @ORM\JoinColumn(name="forma_pago_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     * */
    protected $formaPago;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\PrecioLista")
     * @ORM\JoinColumn(name="precio_lista_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $precioLista;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Moneda")
     * @ORM\JoinColumn(name="moneda_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $moneda;

    /**
     * @var string $cotizacion
     * @ORM\Column(name="cotizacion", type="decimal", scale=2, nullable=true)
     * @Gedmo\Versioned()
     */
    protected $cotizacion = 0;

    /**
     * @ORM\ManyToOne(targetEntity="VentasBundle\Entity\Cliente", inversedBy="notasDebCredVenta")
     * @ORM\JoinColumn(name="cliente_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $cliente;

    /**
     * @var string $nombreCliente
     * @ORM\Column(name="nombre_cliente", type="string", nullable=true)
     * @Gedmo\Versioned()
     */
    protected $nombreCliente;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Parametro")
     * @ORM\JoinColumn(name="tipo_documento_cliente", referencedColumnName="id")
     * @Gedmo\Versioned()
     * */
    protected $tipoDocumentoCliente;

    /**
     * @var string $nroDocumentoCliente
     * @ORM\Column(name="nro_documento_cliente", type="string", length=13, nullable=true)
     * @Gedmo\Versioned()
     */
    protected $nroDocumentoCliente;

    /**
     * @var string $categoriaIva
     * @ORM\Column(name="categoria_iva", type="string", nullable=true)
     */
    protected $categoriaIva;

    /**
     * @var string $percepcionRentas
     * @ORM\Column(name="percepcion_rentas", type="decimal", precision=20, scale=2, nullable=true)
     */
    protected $percepcionRentas;

    /**
     * @ORM\Column(name="concepto", type="text", nullable=true)
     * @Gedmo\Versioned()
     */
    protected $concepto;

    /**
     * @ORM\ManyToOne(targetEntity="VentasBundle\Entity\FacturaElectronica")
     * @ORM\JoinColumn(name="ventas_factura_electronica_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $comprobanteAsociado;

    /**
     * @var datetime $periodoAsocDesde
     * @ORM\Column(name="periodo_asoc_desde", type="datetime", nullable=true)
     * @Gedmo\Versioned()
     */
    private $periodoAsocDesde;

    /**
     * @var datetime $periodoAsocHasta
     * @ORM\Column(name="periodo_asoc_hasta", type="datetime", nullable=true)
     * @Gedmo\Versioned()
     */
    private $periodoAsocHasta;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\UnidadNegocio")
     * @ORM\JoinColumn(name="unidad_negocio_id", referencedColumnName="id")
     */
    protected $unidadNegocio;

    /**
     * @ORM\OneToMany(targetEntity="VentasBundle\Entity\NotaDebCredDetalle", mappedBy="notaDebCred",cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $detalles;

    /**
     * @ORM\OneToMany(targetEntity="VentasBundle\Entity\CobroDetalle", mappedBy="notaDebCred",cascade={"persist", "remove"},orphanRemoval=true)
     */
    protected $cobroDetalles;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var datetime $updated
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var User $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

    /**
     * Constructor
     */
    public function __construct() {
        $this->detalles = new \Doctrine\Common\Collections\ArrayCollection();
        $this->signo = '+';
        $this->estado = 'ACREDITADO';
        $this->cotizacion = 1;
    }

    public function getPagoTxt() {
        return ($this->getFormaPago()->getCuentaCorriente()) ? '' : $this->getFormaPago()->getNombre();
    }

    public function getTextoPagosParaFactura() {
        $txt = '';
        foreach ($this->cobroDetalles as $det) {
            $aux = ($txt) ? ' - ' : '';
            $monto = $det->getMoneda()->getSimbolo() . ' ' . $det->getImporte();
            switch ($det->getTipoPago()) {
                case 'EFECTIVO':
                    $txt = $txt . $aux . 'EFECTIVO: ' . $monto;
                    break;
                case 'CHEQUE':
                    $txt = $txt . $aux . 'CHEQUE: ' . $monto;
                    break;
                case 'TARJETA':
                    $txt = $txt . $aux . $det->getDatosTarjeta()->getTarjeta()->getNombre() . ': ' . $monto;
                    break;
                case 'TRANSFERENCIA':
                    $txt = $txt . $aux . 'TRANSFERENCIA: ' . $monto;
                    break;
            }
        }
        return $txt;
    }

    public function __toString() {
        return $this->getNotaElectronica()->getComprobanteTxt();
    }

    public function getSignoNota() {
        return ($this->signo == '-') ? 'Crédito' : 'Débito';
    }

    public function getClienteTxt() {
        $nombre = $this->getCliente()->getNombre();
        if ($this->nombreCliente) {
            $nombre = $nombre . ' - ' . $this->nombreCliente;
        }
        return $nombre;
    }

    public function getNombreClienteTxt() {
        return $this->getNombreCliente() ? $this->getNombreCliente() : $this->getCliente()->getNombre();
    }

    /**
     *  TOTALIZADOS DE LA OPERACION
     */
    public function getSubTotal() {
        $total = 0;
        foreach ($this->detalles as $item) {
            $total = $total + $item->getTotalItem();
        }
        return $total;
    }

    public function getTotalDescuentoRecargo() {
        $total = 0;
        $categIva = $this->getCategoriaIva();
        if ($categIva == 'I' || $categIva == 'M') {
            // suma de descuentos x item
            foreach ($this->detalles as $item) {
                $total = $total + $item->getTotalDtoRecItem();
            }
            $total = $total / $this->getCotizacion();
        }
        else {
            // descuento sobre el subtotal
            $total = $this->getSubTotal() * ( $this->getDescuentoRecargo() / 100 );
        }
        return round(($total), 2);
    }

    public function getTotalIva() {
        $total = 0;
        foreach ($this->detalles as $item) {
            $total = $total + $item->getTotalIvaItem();
        }
        return round(($total / $this->getCotizacion()), 2);
    }

    public function getTotalIibb() {
        $monto = $this->getSubTotal() + $this->getTotalDescuentoRecargo();
        return $monto * $this->getPercepcionRentas() / 100;
    }

    public function getMontoTotal() {
        $categIva = $this->getCategoriaIva();
        if ($categIva == 'I' || $categIva == 'M') {
            // total con iva e iibb
            $total = $this->getSubTotal() + $this->getTotalDescuentoRecargo() + $this->getTotalIva();
            if ($this->getPercepcionRentas() > 0) {

src/VentasBundle/Resources/views/NotaDebCred/block-select-comprobanteasociado.html.twig
<div class="selectorComprobanteAsociado">
  <label>Comprobante Asociado:</label>
  <select id="ventasbundle_notadebcred_comprobanteAsociado" style="width:90%" name="ventasbundle_notadebcred_comprobanteAsociado" data-urlselect="{{ path('get_autocomplete_facturas') }}" data-urlitems="{{ path('get_items_comprobante') }}" data-urltiposvalidos="{{ path('get_tipos_comprobante_valido') }}">
    <option value="{{ entity.comprobanteAsociado.id is defined ? entity.comprobanteAsociado.id : entity.comprobanteAsociado }}" selected="selected">{{ entity.comprobanteAsociado }}</option>
  </select>
</div>

src/VentasBundle/Resources/views/NotaDebCred/index.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block pageheader %}
<style type="text/css">
.select2-selection__clear {
   left:-20px;
}
</style>
<div class="pageheader notab">
    <h1 class="pagetitle">Notas de Débito/Crédito</h1>
    <span class="pagedesc">Relación con Clientes</span>
</div><!--pageheader-->
{% endblock %}
{% block contentwrapper %}
{% include "AppBundle::notificacion.html.twig" %}

<div id="contentwrapper" class="contentwrapper">
    <div>
        <form id="printform" name="printform" target="_blank"  action="{{ path("print_ventas_list_notadebcred") }}" method="post">
            <input type="hidden" id="clienteid" name="clienteid"/>
            <input type="hidden" id="fdesde" name="fdesde"/>
            <input type="hidden" id="fhasta" name="fhasta"/>
            <input type="hidden" id="searchterm" name="searchterm"/>
            <input type="hidden" id="datalist" name="datalist"/>
            <button class="stdbtn floatright hidden" type="submit" >Imprimir</button>
        </form>
        <form id="searchform" action="{{ path('ventas_notadebcred') }}" method="get" style="display:flex; justify-content: space-between; margin-bottom:10px">

            {% include "VentasBundle:Partial:_partial-select2-cliente.html.twig" with { 'allowclear':true }  %}

            <div style="justify-content: flex-start">
                &nbsp;&nbsp;&nbsp;
                <label><strong>Fecha: </strong></label>
                <input type="text" class="width100 datepicker" title="Fecha desde" value="{{desde}}" name="desde" id="desde" />
                <input type="text" class="width100 datepicker" title="Fecha hasta" value="{{hasta}}" name="hasta" id="hasta" />
                <a href="javascript:void(0)" class="editar btn btnaction btn_search" onClick="jQuery('#searchform').submit();" title="Buscar"></a>
            </div>

            <div style="align-content: flex-start;" >
            {% if apertura|length %}
                    {% if app.user.access(app.session.get('unidneg_id'),'ventas_notadebcred') %}
                        <button type="button" class="stdbtn btn_red" onclick="crearNota('CRE')" style="padding:10px 20px"> NOTA CRÉDITO </button>
                        <button type="button" class="stdbtn btn_blue" onclick="crearNota('DEB')" style="padding:10px 20px"> NOTA DÉBITO </button>
                    {# {% else %} &nbsp; #}
                    {% endif %}
                {# {% else %} #}
            {% else %}
                {% if app.session.get('caja') %}
                    {% if  app.user.access(app.session.get('unidneg_id'),'ventas_caja_apertura') %}
                            {% set urlApertura = path('ventas_apertura_new') %}
                            <a href="javascript:void(0)" onclick="aperturaCajaVentas('{{ urlApertura }}','true')" class="btn btn_orange btn_lock" title="Debe abrir la caja para realizar cobros">
                                <span style="font-size: 14px;">APERTURA DE CAJA</span>
                            </a>
                    {% else %}
                        <div class="external-event" style="background-color:orangered;cursor:pointer" title="Debe abrir la caja para realizar cobros">CAJA CERRADA</div>
                    {% endif %}
                {% endif %}
            {% endif %}
            </div>
        </form>
    </div><!-- button -->
        <table cellpadding="0" cellspacing="0" border="0" class="stdtable" id="dyntable2">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Cliente</th>
                    <th>Comprobante</th>
                    <th>CAE</th>
                    <th>Total</th>
                    <th>Estado</th>
                    <th>Usuario</th>
                    <th class="nosort actionbutton addbutton">&nbsp</th>
                </tr>
            </thead>
            <tbody>
               {% for entity in entities %}
                <tr {% if entity.estado=='ELIMINADO' %} class="deleted" {%endif%}>
                    <td><span class="hidden">{{ entity.fecha|date('YmdHmi') }}</span>{{ entity.fecha|date('d-m-Y') }}</td>
                    <td>{{ entity.nombreClienteTxt }}</td>
                    <td>
                    {% if entity.notaElectronica %}
                        {{ entity.notaElectronica.comprobanteTxt }}
                    {% elseif app.user.access(app.session.get('unidneg_id'),'ventas_notadebcred_print') and entity.estado != 'ELIMINADO'%}
                        {% if app.session.get('caja') and app.session.get('caja')['apertura'] %}
                            <a href="{{ path('ventas_notadebcred_edit',{ 'id': entity.id }) }}" type="button" class="stdbtn btn_red " title="Facturar">Facturar</a>
                        {% endif %}
                    {% endif %}
                    </td>
                    <td>{{ entity.notaElectronica ? entity.notaElectronica.cae : ''}}</td>
                    <td class="alignright"><span style="float:left">{{entity.moneda.simbolo}}</span>{{ entity.montoTotal|number_format(2,',','.') }}</td>
                    <td>{{ entity.estado == 'CREADO' ? 'PENDIENTE' : (entity.estado == 'ACREDITADO' ? 'FACTURADO' : entity.estado) }}</td>
                    <td>{{ entity.createdBy.username }}</td>
                    <td class="buttons">
                        {% if app.user.access(app.session.get('unidneg_id'),'ventas_notadebcred') %}
                            <a href="{{ path('ventas_notadebcred_show', { 'id': entity.id }) }}" class="editar btn btnaction btn_folder" title="Ver Nota"></a>
                            {% if entity.notaElectronica %}
                                {% if entity.notaElectronica.cae %}
                                <a href="javascript:void(0)" url="{{ path('ventas_factura_print', { 'id': entity.id, 'entity': 'NotaDebCred' })}}" class="editar btn btnaction btn_print" id="nota{{entity.id}}" title="Imprimir Comprobante"></a>
                                {% endif %}
                            {% elseif entity.estado != 'ELIMINADO' %}
                                <a href="{{ path('ventas_notadebcred_delete', { 'id': entity.id }) }}" onclick="confirm('Confirma la eliminación! Esta acción no se puede deshacer')" class="btn btnaction btn_trash btn_yellow" title="Eliminar"></a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
               {% endfor %}
            </tbody>
        </table>
</div>
 {% endblock %}
{% block extra_javascripts %}
{% include "AppBundle::block-list-js.html.twig" %}
<script type="text/javascript">
jQuery(document).ready(function($){

    $('.datepicker').datepicker({dateFormat: 'dd-mm-yy'});

    var oTable = $('#dyntable2').dataTable();
    oTable.fnSort( [ [0,'desc'],[2,'desc'] ] );

    $('#printform').on('submit',function(){
        $('#clienteid').val($('#selectCliente').val());
        $('#fdesde').val($('#desde').val());
        $('#fhasta').val($('#hasta').val());
        $('#searchterm').val( $('#dyntable2_filter input').val() );
        var datos = [];
        oTable.api().rows( { search:'applied' } ).data().each(function(value, index) {
            var i = value[2].indexOf('</span>');
            if( i >-1 ){
                var fecha = value[2].substr(i+7);
                value[2]=fecha;
            }
            value.splice(5);
            datos[index] = value;
        });
        $('#datalist').val(JSON.stringify(datos));
    });
    const printpdf = '{{printpdf}}';
    if( printpdf ){
      $('#nota'+printpdf).click()
      {# $('.btn_search').click() #}
    }
});
function crearNota(tipo){
    location.href = "{{ path('ventas_notadebcred_new') }}?tipo=" + tipo
}
</script>
{% endblock %}