src/VentasBundle/Entity/Cobro.php
<?php

namespace VentasBundle\Entity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * VentasBundle\Entity\Cobro
 * @ORM\Table(name="ventas_cobro")
 * @ORM\Entity(repositoryClass="VentasBundle\Entity\CobroRepository")
 * @Gedmo\Loggable()
 */
class Cobro {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer $nroOperacion
     * @ORM\Column(name="nro_operacion", type="integer")
     */
    protected $nroOperacion = '';

    /**
     * @var datetime $fechaCobro
     * @ORM\Column(name="fecha_cobro", type="datetime", nullable=false)
     * @Gedmo\Versioned()
     */
    protected $fechaCobro;
    /**
     * Estados: PENDIENTE - FINALIZADO - ANULADO
     */

    /**
     * @var string $estado
     * @ORM\Column(name="estado", type="string")
     * @Gedmo\Versioned()
     */
    protected $estado = 'PENDIENTE';

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\UnidadNegocio")
     * @ORM\JoinColumn(name="unidad_negocio_id", referencedColumnName="id")
     */
    protected $unidadNegocio;

    /**
     * @ORM\ManyToOne(targetEntity="VentasBundle\Entity\Cliente", inversedBy="cobros")
     * @ORM\JoinColumn(name="cliente_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $cliente;

    /**
     * @var string $nombreCliente
     * @ORM\Column(name="nombre_cliente", type="string", nullable=true)
     * @Gedmo\Versioned()
     */
    protected $nombreCliente;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Parametro")
     * @ORM\JoinColumn(name="tipo_documento_cliente", referencedColumnName="id")
     * @Gedmo\Versioned()
     * */
    protected $tipoDocumentoCliente;

    /**
     * @var string $nroDocumentoCliente
     * @ORM\Column(name="nro_documento_cliente", type="string", length=13, nullable=true)
     * @Gedmo\Versioned()
     */
    protected $nroDocumentoCliente;

    /**
     * @var string $direccionCliente
     * @ORM\Column(name="direccion_cliente", type="string", nullable=true)
     * @Gedmo\Versioned()
     */
    protected $direccionCliente;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\FormaPago")
     * @ORM\JoinColumn(name="forma_pago_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     * */
    protected $formaPago;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Moneda")
     * @ORM\JoinColumn(name="moneda_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $moneda;

    /**
     * @var string $cotizacion
     * @ORM\Column(name="cotizacion", type="decimal", precision=20, scale=2, nullable=true)
     * @Gedmo\Versioned()
     */
    protected $cotizacion = 0;

    /**
     * @var datetime $periodoAsocDesde
     * @ORM\Column(name="periodo_asoc_desde", type="datetime", nullable=true)
     * @Gedmo\Versioned()
     */
    private $periodoAsocDesde;

    /**
     * @var datetime $periodoAsocHasta
     * @ORM\Column(name="periodo_asoc_hasta", type="datetime", nullable=true)
     * @Gedmo\Versioned()
     */
    private $periodoAsocHasta;

    /**
     * @var datetime $fechaVtoPago
     * @ORM\Column(name="fecha_vto_pago", type="datetime", nullable=true)
     * @Gedmo\Versioned()
     */
    private $fechaVtoPago;

    /**
     * @ORM\OneToMany(targetEntity="VentasBundle\Entity\CobroDetalle", mappedBy="cobro",cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $detalles;

    /**
     * @ORM\OneToOne(targetEntity="VentasBundle\Entity\Venta", inversedBy="cobro")
     * @ORM\JoinColumn(name="venta_id", referencedColumnName="id")
     */
    protected $venta;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var datetime $updated
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var User $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

    /**
     * @ORM\OneToOne(targetEntity="VentasBundle\Entity\FacturaElectronica", mappedBy="cobro", cascade={"persist"})
     */
    protected $facturaElectronica;

    public function getPagoTxt() {
        return ($this->getFormaPago()->getCuentaCorriente()) ? '' : $this->getFormaPago()->getNombre();
    }

    //* datos para la impresion de la factura electronica
    public function getTextoPagosParaFactura() {
        $txt = '';
        foreach ($this->detalles as $det) {
            $aux = ($txt) ? ' - ' : '';
            $monto = $det->getMoneda()->getSimbolo() . ' ' . $det->getImporte();
            switch ($det->getTipoPago()) {
                case 'EFECTIVO':
                    $txt = $txt . $aux . 'EFECTIVO: ' . $monto;
                    break;
                case 'CHEQUE':
                    $txt = $txt . $aux . 'CHEQUE: ' . $monto;
                    break;
                case 'TARJETA':
                    $txt = $txt . $aux . $det->getDatosTarjeta()->getTarjeta()->getNombre() . ': ' . $monto;
                    break;
                case 'TRANSFERENCIA':
                    $txt = $txt . $aux . 'TRANSFERENCIA: ' . $monto;
                    break;
            }
        }
        return $txt;
    }

    public function getNombreClienteTxt() {
        return $this->getNombreCliente() ? $this->getNombreCliente() : $this->getCliente()->getNombre();
    }

    public function getSubtotal() {
        return $this->getVenta()->getSubtotal();
    }

    public function getRefVenta() {
        return "Ref. #" . $this->getVenta()->getNroOperacion();
    }

    public function getDescuentoRecargo() {
        return $this->getVenta()->getDescuentoRecargo();
    }

    public function getTotalDescuentoRecargo() {
        return $this->getVenta()->getTotalDescuentoRecargo();
    }

    public function getTotalIva() {
        return $this->getVenta()->getTotalIva();
    }

    public function getTotalIibb() {
        return $this->getVenta()->getTotalIibb();
    }

    public function getVentaDetalles() {
        return $this->getVenta()->getDetalles();
    }

    public function getConcepto() {
        return $this->getVenta()->getConcepto();
    }

    public function getMontoTotal() {
        return $this->getVenta()->getMontoTotal();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nroOperacion
     *
     * @param integer $nroOperacion
     * @return Cobro
     */
    public function setNroOperacion($nroOperacion) {
        $this->nroOperacion = $nroOperacion;

        return $this;
    }

    /**
     * Get nroOperacion
     *
     * @return integer
     */
    public function getNroOperacion() {
        return $this->nroOperacion;
    }

    /**
     * Set fechaCobro
     *
     * @param \DateTime $fechaCobro
     * @return Cobro
     */
    public function setFechaCobro($fechaCobro) {
        $this->fechaCobro = $fechaCobro;

        return $this;
    }

    /**
     * Get fechaCobro
     *
     * @return \DateTime
     */
    public function getFechaCobro() {
        return $this->fechaCobro;
    }

    /**
     * Set estado
     *
     * @param string $estado
     * @return Cobro
     */
    public function setEstado($estado) {
        $this->estado = $estado;

        return $this;
    }

    /**
     * Get estado
     *
     * @return string
     */
    public function getEstado() {
        return $this->estado;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Cobro
     */
    public function setCreated($created) {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated() {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return Cobro
     */
    public function setUpdated($updated) {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated() {
        return $this->updated;
    }

    /**
     * Set unidadNegocio
     *
     * @param \ConfigBundle\Entity\UnidadNegocio $unidadNegocio
     * @return Cobro
     */
    public function setUnidadNegocio(\ConfigBundle\Entity\UnidadNegocio $unidadNegocio = null) {
        $this->unidadNegocio = $unidadNegocio;

        return $this;
    }

    /**
     * Get unidadNegocio
     *
     * @return \ConfigBundle\Entity\UnidadNegocio
     */
    public function getUnidadNegocio() {
        return $this->unidadNegocio;
    }

    /**
     * Set cliente
     *
     * @param \VentasBundle\Entity\Cliente $cliente
     * @return Cobro
     */
    public function setCliente(\VentasBundle\Entity\Cliente $cliente = null) {
        $this->cliente = $cliente;

        return $this;
    }

    /**
     * Get cliente
     *
     * @return \VentasBundle\Entity\Cliente
     */
    public function getCliente() {
        return $this->cliente;
    }

    /**
     * Set formaPago
     *
     * @param \ConfigBundle\Entity\FormaPago $formaPago
     * @return Cobro
     */
    public function setFormaPago(\ConfigBundle\Entity\FormaPago $formaPago = null) {
        $this->formaPago = $formaPago;

        return $this;
    }

    /**
     * Get formaPago
     *

src/VentasBundle/Entity/FacturaDetalle.php
<?php

namespace VentasBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * VentasBundle\Entity\FacturaDetalle
 * @ORM\Table(name="ventas_factura_detalle")
 * @ORM\Entity()
 */
class FacturaDetalle {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer $orden
     * @ORM\Column(name="orden", type="integer",nullable=true)
     */
    protected $orden;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Producto")
     * @ORM\JoinColumn(name="producto_id", referencedColumnName="id")
     */
    protected $producto;

    /**
     * @var integer $cantidad
     * @ORM\Column(name="cantidad", type="decimal", precision=20, scale=2)
     */
    protected $cantidad = 1;

    /**
     * @ORM\Column(name="bulto", type="boolean", nullable=true)
     */
    protected $bulto = false;

    /**
     * @var integer $cantidadxBulto
     * @ORM\Column(name="cantidad_x_bulto", type="integer", nullable=true )
     */
    protected $cantidadxBulto;

    /**
     * @var integer $precio
     * @ORM\Column(name="precio", type="decimal", precision=20, scale=2 )
     */
    protected $precio;

    /**
     * @var integer $iva
     * @ORM\Column(name="iva", type="decimal", precision=20, scale=2 )
     */
    protected $iva;

    /**
     * @var integer $descuento
     * @ORM\Column(name="descuento", type="decimal", precision=20, scale=2 )
     */
    protected $descuento = 0;

    /**
     * @ORM\ManyToOne(targetEntity="VentasBundle\Entity\Factura", inversedBy="detalles")
     * @ORM\JoinColumn(name="ventas_factura_id", referencedColumnName="id")
     */
    protected $factura;

    /*
     * DATOS PARA AFIP
     */

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\AfipAlicuota")
     * @ORM\JoinColumn(name="afip_alicuota_id", referencedColumnName="id")
     * */
    protected $afipAlicuota;

    /**
     * Constructor
     */
    public function __construct() {
        //$this->iva = 21;
        $this->descuento = 0;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set orden
     *
     * @param integer $orden
     * @return FacturaDetalle
     */
    public function setOrden($orden) {
        $this->orden = $orden;

        return $this;
    }

    /**
     * Get orden
     *
     * @return integer
     */
    public function getOrden() {
        return $this->orden;
    }

    /**
     * Set cantidad
     *
     * @param integer $cantidad
     * @return FacturaDetalle
     */
    public function setCantidad($cantidad) {
        $this->cantidad = $cantidad;

        return $this;
    }

    /**
     * Get cantidad
     *
     * @return integer
     */
    public function getCantidad() {
        return $this->cantidad;
    }

    /**
     * Set precio
     *
     * @param string $precio
     * @return FacturaDetalle
     */
    public function setPrecio($precio) {
        $this->precio = $precio;

        return $this;
    }

    /**
     * Get precio
     *
     * @return string
     */
    public function getPrecio() {
        return $this->precio;
    }

    /**
     * Set iva
     *
     * @param string $iva
     * @return FacturaDetalle
     */
    public function setIva($iva) {
        $this->iva = $iva;

        return $this;
    }

    /**
     * Get iva
     *
     * @return string
     */
    public function getIva() {
        return $this->iva;
    }

    /**
     * Set descuento
     *
     * @param string $descuento
     * @return FacturaDetalle
     */
    public function setDescuento($descuento) {
        $this->descuento = $descuento;

        return $this;
    }

    /**
     * Get descuento
     *
     * @return string
     */
    public function getDescuento() {
        return $this->descuento;
    }

    /**
     * Set producto
     *
     * @param \AppBundle\Entity\Producto $producto
     * @return FacturaDetalle
     */
    public function setProducto(\AppBundle\Entity\Producto $producto = null) {
        $this->producto = $producto;

        return $this;
    }

    /**
     * Get producto
     *
     * @return \AppBundle\Entity\Producto
     */
    public function getProducto() {
        return $this->producto;
    }

    /**
     * Set factura
     *
     * @param \VentasBundle\Entity\Factura $factura
     * @return FacturaDetalle
     */
    public function setFactura(\VentasBundle\Entity\Factura $factura = null) {
        $this->factura = $factura;

        return $this;
    }

    /**
     * Get factura
     *
     * @return \VentasBundle\Entity\Factura
     */
    public function getFactura() {
        return $this->factura;
    }

    /** Calculos * */
    public function getSubTotal() {
        return $this->precio * $this->cantidad;
    }

    public function getMontoDescuento() {
        return $this->getSubTotal() * ($this->descuento / 100);
    }

    /*   public function getMontoIva(){
      return ( $this->getSubTotal() - $this->getMontoDescuento() ) * ($this->iva/100);
      } */

    public function getTotal() {
        return ($this->getSubTotal() - $this->getMontoDescuento()) + $this->getIva();
    }

    // Cantidad para mostrar como texto
    public function getCantidadTxt() {
        if ($this->bulto) {
            return $this->getCantidad() . ' x ' . $this->getCantidadxBulto() . ' ' . $this->getProducto()->getUnidadMedida()->getNombre();
        }
        else {
            return $this->getCantidad() . ' ' . $this->getProducto()->getUnidadMedida()->getNombre();
        }
    }

    /**
     * Set bulto
     *
     * @param boolean $bulto
     * @return FacturaDetalle
     */
    public function setBulto($bulto) {
        $this->bulto = $bulto;

        return $this;
    }

    /**
     * Get bulto
     *
     * @return boolean
     */
    public function getBulto() {
        return $this->bulto;
    }

    /**
     * Set cantidadxBulto
     *
     * @param string $cantidadxBulto
     * @return FacturaDetalle
     */
    public function setCantidadxBulto($cantidadxBulto) {
        $this->cantidadxBulto = $cantidadxBulto;

        return $this;
    }

    /**
     * Get cantidadxBulto
     *
     * @return string
     */
    public function getCantidadxBulto() {
        return $this->cantidadxBulto;
    }

    /**
     * Set afipAlicuota
     *
     * @param \ConfigBundle\Entity\AfipAlicuota $afipAlicuota
     * @return FacturaDetalle
     */
    public function setAfipAlicuota(\ConfigBundle\Entity\AfipAlicuota $afipAlicuota = null) {
        $this->afipAlicuota = $afipAlicuota;

        return $this;
    }

    /**
     * Get afipAlicuota
     *
     * @return \ConfigBundle\Entity\AfipAlicuota
     */
    public function getAfipAlicuota() {
        return $this->afipAlicuota;
    }

}

src/VentasBundle/Resources/views/Partial/_partial-datos-cf.html.twig
<div class="datos-cf" {% if not entity.cliente.consumidorfinal %} style="display:none" {% endif %} >
    <div style="width: 50%; ">
        {{ form_label(form.nombreCliente)}}
        {{ form_widget(form.nombreCliente)}}
    </div>
    <div style="width: 18%;">
        {{ form_row(form.tipoDocumentoCliente, { 'attr': {'class' : 'select2','style':'width:100%','data-allow-clear':'true','data-placeholder':'' } })}}
    </div>
    <div style="width: 18%;">
        {{ form_row(form.nroDocumentoCliente)}}
    </div>
    {% if form.direccionCliente is defined and false %}
    <div style="width: 33%;">
        {{ form_row(form.direccionCliente)}}
    </div>
    {% endif %}
</div>

src/VentasBundle/Resources/views/Partial/_partial-datos-cliente.html.twig
<div class="datos-cliente datos-cf">

{% if item.consumidorFinal %}

  {% if detallado is defined %}

    <div style="width: 50%; ">
        <label>Nombre: </label>
        <input type="text" name="ventasbundle_nombreCliente" id="ventasbundle_nombreCliente" value="{{detallado.nombreCliente}}"/>
    </div>
    <div style="width: 18%;">
        <label>Tipo Documento: </label>
        <select class="select2" id="ventasbundle_tipoDocumentoCliente"
            name="ventasbundle_tipoDocumentoCliente" style="width:100%"
            url_select = "{{ path('get_parametro_autocomplete') }}"
        >
        {% if detallado.tipoDocumentoCliente.id is defined %}
          <option value="{{detallado.tipoDocumentoCliente.id}}" selected="selected">{{detallado.tipoDocumentoCliente}}</option>
        {% endif %}
        </select>
    </div>
    <div style="width: 18%;">
        <label>N° Documento: </label>
        <input type="text" name="ventasbundle_nroDocumentoCliente" id="ventasbundle_nroDocumentoCliente" value="{{detallado.nroDocumentoCliente}}"/>
    </div>

  {% else %}

    <div style="width: 80%; ">
        <input type="text" name="ventasbundle_nombreCliente" id="ventasbundle_nombreCliente" placeholder="Nombre y Apellido" value="{{ nombreCliente is defined ? nombreCliente : '' }}"/>
    </div>

  {% endif %}

{% else %}

    <label> CUIT: </label>
    <span class="cuitcliente {% if cuitvalido is defined %} {{ not cuitvalido ? 'cuitinvalido' : '' }} {% endif %}">
      {{item.cuit}}
    </span>

    <label> IVA: </label>
      {{ item.condicionIva ? item.condicionIva.nombre|upper : "No definido" }}

    <label> RENTAS: </label>
    {{ item.categoriaRentas ? item.categoriaRentas.nombre|upper : "No definido" }}

    {% if item.direccion is defined %}
      <label> DIRECCIÓN: </label> {{item.domicilioCompleto|upper}}
    {% endif %}

{% endif %}

</div>

src/VentasBundle/Resources/views/Partial/_partial-datos-formapago.html.twig
<div class="datos-formapago"
  data-porcentajeRecargo="{{item.porcentajeRecargo}}"
  data-tipoPago="{{item.tipoPago}}"
  data-ctacte ="{{item.cuentaCorriente}}"
>
  {% set lblPorcentajeRecargo =  (item.porcentajeRecargo > 0) ? 'RECARGO:' : 'DESCUENTO:' %}
  <label class="lblPorcentajeRecargo"> {{ lblPorcentajeRecargo }} </label>
    {{ item.porcentajeRecargo|abs ~ ' %' }}
  {% if item.cuotas > 0 %}
      <label> CUOTAS:</label>{{item.cuotas}}
  {% endif %}
  {% if item.plazo > 0 %}
      <label> PLAZO:</label>{{item.plazo ~ ' ' ~ item.vencimiento|upper }}
  {% endif %}
</div>

src/VentasBundle/Resources/views/Partial/_partial-datos-moneda.html.twig
{% if item.cotizacion != 1 %}
    <label> TIPO DE CAMBIO: </label> {{item.cotizacion }}
{% endif %}
<input type="hidden" id="simbolo" name="simbolo" value="{{item.simbolo}}" />

src/VentasBundle/Resources/views/Partial/_partial-detalle.html.twig
<table cellpadding="0" cellspacing="0" border="0" class="detalle stdtable noaction">
    <thead>
        <tr>
            <th style="width:3%;">#</th>
            <th>Producto</th>
            <th style="width:12%;">Cant.</th>
            <th style="width:10%;">Precio Unit.</th>
            <th style="width:10%;">SubTotal</th>
            <th style="width:3%;">
                <a href="javascript:void(0)" id="linkAdd" tabindex="0"  title="Agregar" onclick="addNewItem()"><span class="add-item-button">+</span></a>
            </th>
        </tr>
    </thead>
    <tbody data-index="{{form.detalles | length }}" data-prototype="{% filter escape %}{% include 'VentasBundle:Partial:item-prototype.html.twig' with {'item':form.detalles.vars.prototype} %}{% endfilter %}">
    {% for det in form.detalles %}

        {% include 'VentasBundle:Partial:item-prototype.html.twig' with {'item': det} %}
        
    {% endfor %}
    </tbody>

    <tfoot>
        <tr>
            <th colspan="4" style="text-align:right">&nbsp; </th>
            <th class="cktotal alignright" id="subtotalTh"></th>
            <th style="text-align:center;"></th>
        </tr>
    </tfoot>

</table>

src/VentasBundle/Resources/views/Partial/_partial-notifmsg.html.twig
<div class="notifmsg info png_bg" style="margin-top:50px; background-position:10px 7px !important">
  <div style="padding: 5px 10px 5px 36px">
    <small>
      {% if 'cliente' in shortcuts %}
        Ctrl+Alt+C = Cliente <strong class="divnotif">|</strong>
      {% endif %}

      {% if 'formapago' in shortcuts %}
        Ctrl+Alt+F = Forma de Pago <strong class="divnotif">|</strong>
      {% endif %}

      {% if 'detalle' in shortcuts %}
        Ctrl+Alt+D = Ver Detalle de Items <strong class="divnotif">|</strong>
      {% endif %}

      {% if '+pago' in shortcuts %}
        Ctrl+Alt+P = Agregar pago <strong class="divnotif">|</strong>
      {% endif %}

      {% if '+producto' in shortcuts %}
        + = Agregar producto <strong class="divnotif">|</strong>
      {% endif %}

      Ctrl+Alt+G = Guardar

    </small>
  </div>
</div>

src/VentasBundle/Resources/views/Partial/_partial-resumen.html.twig
{% set simbolo = ( entity.moneda is defined ) ? entity.moneda.simbolo : '$' %}
{% set cativa = (entity.cliente.condicionIva) ? entity.cliente.condicionIva.codigo : 'C' %}
{% set showiva = (cativa == 'I' or cativa == 'M') %}
<table cellpadding="0" cellspacing="0" border="0" class="stdtable noaction">
  <thead>
    <tr class="resumen">
      <th style="width:18%">
        Subtotal: <span class="simbolo">{{simbolo}}</span>&nbsp;
            <span id="importeSubtotal" >{{ (entity.subTotal)|number_format(2,',','.')}}</span>.-
      </th>
      <th >
        Descuento/Recargo [
            {% if form is defined %}
                {% set disabledDescuentoRecargo = app.user.access(app.session.get('unidneg_id'),'ventas_venta_descuento') ? false : true %}
                {{ form_widget(form.descuentoRecargo, {'attr': {'readonly': disabledDescuentoRecargo, 'class':'width50'} }) }}
            {% else %}
                {{ entity.descuentoRecargo|number_format(2,',','.') }}
            {% endif %}
        %]:
        <span class="simbolo">{{simbolo}}</span>&nbsp;
        <span id="importeRecargo">{{ entity.totalDescuentoRecargo|number_format(2,',','.') }}</span>.-
      </th>
      <th id="ivaTd" style=" {% if not showiva %} display:none; {% endif %} width:16%">
        IVA: <span class="simbolo">{{simbolo}}</span>&nbsp;
        <span id="importeIVA">{{ entity.totalIva|number_format(2,',','.') }}</span>.-
      </th>
      <th id="iibbTd" style="{% if entity.cliente.percepcionRentas == 0 %} display:none; {% endif %}width:20%">
          Perc.IIBB [<span id="percrentas">{{entity.cliente.percepcionRentas|number_format(2,'.',',')}}</span>%]: <span class="simbolo">{{simbolo}}</span>&nbsp;
        <span id="importeIIBB">{{ entity.totalIibb|number_format(2,',','.') }}</span>.-
      </th>
      <th style="width:18%" class="gralTotalTd red">
        TOTAL: <span class="simbolo">{{simbolo}}</span>&nbsp;<span id="importeTotal">
          {{ entity.montoTotal|number_format(2,',','.')}}
        </span>.-
      </th>
    </tr>
  </thead>
</table>

src/VentasBundle/Resources/views/Partial/_partial-show-detalle.html.twig
<table class="stdtable noaction" cellspacing="0" cellpadding="0" border="0">
    <thead>
        <tr>
            <th style="width:3%;">#</th>
            <th>Producto</th>
            <th style="width:12%;">Cant.</th>
            <th style="width:10%;">Precio Unit.</th>
            <th style="width:10%;">SubTotal</th>
        </tr>
    </thead>
    <tbody>
    {% for detalle in entity.detalles %}
        <tr class="item">
            <td class="ordTd">{{loop.index}}</td>
            <td class="prodTd">
                <strong>{{ detalle.nombreProducto }} | {{detalle.producto.codigo}}</strong>
            </td>
            <td class="cantTd alignright">{{ detalle.cantidad|number_format(2,',','.') }} {{detalle.producto.unidadmedida.nombre}}</td>
            <td class="precTd alignright">{{ detalle.precioUnitarioItem|number_format(2,',','.') }}</td>
            <td class="itmSubtotalTd alignright">{{ detalle.totalItem|number_format(2,',','.') }}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="4" style="text-align:right">&nbsp; </th>
            <th class="cktotal alignright" id="subtotalTh">{{entity.subTotal|number_format(2,',','.') }}</th>
        </tr>
    </tfoot>
</table>