src/VentasBundle/Entity/Presupuesto.php
<?php

namespace VentasBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * VentasBundle\Entity\Presupuesto
 * @ORM\Table(name="ventas_presupuesto")
 * @ORM\Entity(repositoryClass="VentasBundle\Entity\PresupuestoRepository")
 * @Gedmo\Loggable()
 */
class Presupuesto {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer $nroPresupuesto
     * @ORM\Column(name="nro_presupuesto", type="string", length=30)
     */
    protected $nroPresupuesto;

    /**
     * @var datetime $fechaPresupuesto
     * @ORM\Column(name="fecha_presupuesto", type="datetime", nullable=false)
     * @Gedmo\Versioned()
     */
    private $fechaPresupuesto;

    /**
     * Estados: EMITIDO - IMPRESO - ANULADO
     */

    /**
     * @var string $estado
     * @ORM\Column(name="estado", type="string")
     * @Gedmo\Versioned()
     */
    protected $estado = 'EMITIDO';

    /**
     * @var integer $descuentoRecargo
     * @ORM\Column(name="descuentoRecargo", type="decimal", precision=20, scale=2,nullable=true )
     * @Gedmo\Versioned()
     */
    protected $descuentoRecargo;

    /**
     * @ORM\ManyToOne(targetEntity="VentasBundle\Entity\Cliente", inversedBy="facturasVenta")
     * @ORM\JoinColumn(name="cliente_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $cliente;

    /**
     * @var string $nombreCliente
     * @ORM\Column(name="nombre_cliente", type="string", nullable=true)
     * @Gedmo\Versioned()
     */
    protected $nombreCliente;

    /**
     * @var string $categoriaIva
     * @ORM\Column(name="categoria_iva", type="string", nullable=true)
     */
    protected $categoriaIva;

    /**
     * @var string $percepcionRentas
     * @ORM\Column(name="percepcion_rentas", type="decimal", precision=20, scale=2, nullable=true)
     */
    protected $percepcionRentas;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\FormaPago")
     * @ORM\JoinColumn(name="forma_pago_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     * */
    protected $formaPago;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\PrecioLista")
     * @ORM\JoinColumn(name="precio_lista_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $precioLista;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Deposito")
     * @ORM\JoinColumn(name="deposito_id", referencedColumnName="id")
     * @Gedmo\Versioned()
     */
    protected $deposito;

    /**
     * @ORM\Column(name="descuenta_stock", type="boolean",nullable=true)
     * @Gedmo\Versioned()
     */
    protected $descuentaStock = false;

    /**
     * @ORM\Column(name="tipo", type="string")
     * @Gedmo\Versioned()
     */
    protected $tipo = 'P';

    /**
     * @var integer $validez
     * validez en dias
     * @ORM\Column(name="validez", type="integer")
     */
    protected $validez;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\UnidadNegocio")
     * @ORM\JoinColumn(name="unidad_negocio_id", referencedColumnName="id")
     */
    protected $unidadNegocio;

    /**
     * @ORM\OneToMany(targetEntity="VentasBundle\Entity\PresupuestoDetalle", mappedBy="presupuesto",cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $detalles;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var datetime $updated
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var User $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

    /**
     * Constructor
     */
    public function __construct() {
        $this->detalles = new \Doctrine\Common\Collections\ArrayCollection();
        $this->validez = 1;
    }

    public function __clone() {
        $this->id = null;
    }

    public function getNroPresupuestoTxt() {
        return str_pad($this->nroPresupuesto, 8, "0", STR_PAD_LEFT);
    }

    /**
     *  TOTALIZADOS DE LA OPERACION
     *
      public function getSubTotal() {
      $total = 0;
      foreach ($this->detalles as $item) {
      $total = $total + $item->getTotalItem();
      }
      return $total;
      }
      public function getTotalDescuentoRecargo() {
      $total = $this->getSubTotal() * ( $this->getDescuentoRecargo()/100 );
      return round( ($total ) ,2);
      }
      public function getTotalIva(){
      $total = 0;
      foreach ($this->detalles as $item) {
      $total = $total + $item->getIvaItem();
      }
      return round( $total ,2);
      }
      public function getTotalIibb(){
      $monto = $this->getSubTotal() + $this->getTotalDescuentoRecargo();
      return $monto * $this->getParameter('iibb_percent')/100 ;
      }
      public function getMontoTotal(){
      $total = $this->getSubTotal() + $this->getTotalDescuentoRecargo()  ;
      return round($total,2) ;
      } */

    /**
     *  TOTALIZADOS DE LA OPERACION
     */
    public function getSubTotal() {
        $total = 0;
        foreach ($this->detalles as $item) {
            $total = $total + $item->getTotalItem();
        }
        return $total;
    }

    public function getTotalDescuentoRecargo() {
        $total = 0;
        $categIva = $this->getCategoriaIva();
        if ($categIva == 'I' || $categIva == 'M') {
            // suma de descuentos x item
            foreach ($this->detalles as $item) {
                $total = $total + $item->getTotalDtoRecItem();
            }
        }
        else {
            // descuento sobre el subtotal
            $total = $this->getSubTotal() * ( $this->getDescuentoRecargo() / 100 );
        }
        return round(($total), 2);
    }

    public function getTotalIva() {
        $total = 0;
        foreach ($this->detalles as $item) {
            $total = $total + $item->getTotalIvaItem();
        }
        return round(($total), 2);
    }

    public function getTotalIibb() {
        $monto = $this->getSubTotal() + $this->getTotalDescuentoRecargo();
        return $monto * $this->getPercepcionRentas() / 100;
    }

    public function getMontoTotal() {
        $categIva = $this->getCategoriaIva();
        if ($categIva == 'I' || $categIva == 'M') {
            // total con iva e iibb
            $total = $this->getSubTotal() + $this->getTotalDescuentoRecargo() + $this->getTotalIva();
            if ($this->getPercepcionRentas() > 0) {
                $total = $total + $this->getTotalIibb();
            }
        }
        else {
            // subtotal +/- descuentoRecargo
            $descRec = $this->getSubTotal() * ( $this->getDescuentoRecargo() / 100 );
            $total = $this->getSubTotal() + $descRec;
        }
        return round($total, 2);
    }

    /**
     *  FIN TOTALIZADOS
     */

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nroPresupuesto
     *
     * @param string $nroPresupuesto
     * @return Presupuesto
     */
    public function setNroPresupuesto($nroPresupuesto) {
        $this->nroPresupuesto = $nroPresupuesto;

        return $this;
    }

    /**
     * Get nroPresupuesto
     *
     * @return string
     */
    public function getNroPresupuesto() {
        return $this->nroPresupuesto;
    }

    /**
     * Set fechaPresupuesto
     *
     * @param \DateTime $fechaPresupuesto
     * @return Presupuesto
     */
    public function setFechaPresupuesto($fechaPresupuesto) {
        $this->fechaPresupuesto = $fechaPresupuesto;

        return $this;
    }

    /**
     * Get fechaPresupuesto
     *
     * @return \DateTime
     */
    public function getFechaPresupuesto() {
        return $this->fechaPresupuesto;
    }

    /**
     * Set estado
     *
     * @param string $estado
     * @return Presupuesto
     */
    public function setEstado($estado) {
        $this->estado = $estado;

        return $this;
    }

    /**
     * Get estado
     *
     * @return string
     */
    public function getEstado() {
        return $this->estado;
    }

    /**
     * Set descuentoRecargo
     *
     * @param string $descuentoRecargo
     * @return Presupuesto
     */
    public function setDescuentoRecargo($descuentoRecargo) {
        $this->descuentoRecargo = $descuentoRecargo;

        return $this;
    }

    /**
     * Get descuentoRecargo
     *
     * @return string
     */
    public function getDescuentoRecargo() {
        return $this->descuentoRecargo;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Presupuesto
     */
    public function setCreated($created) {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated() {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return Presupuesto
     */
    public function setUpdated($updated) {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated() {
        return $this->updated;
    }

    /**
     * Set cliente
     *
     * @param \VentasBundle\Entity\Cliente $cliente
     * @return Presupuesto
     */

src/VentasBundle/Form/PresupuestoType.php
<?php

namespace VentasBundle\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;

class PresupuestoType extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
//    $type = $options['attr']['type'];
//        $data = $options['data'];
        $builder
            // ->add('nombreCliente', null, array('required' => false,
            //     'attr'=> array('placeholder'=>'Nombre y Apellido')))
            ->add('precioLista', 'entity', array(
                'class' => 'AppBundle:PrecioLista',
                'required' => true, 'label' => 'LISTA DE PRECIOS: ',
                'choice_label' => 'nombre',
            ))
            ->add('deposito', 'entity', array(
                'class' => 'AppBundle:Deposito',
                'required' => true, 'label' => 'DEPÓSITO: ',
                'choice_label' => 'nombre'
            ))
            ->add('descuentaStock', null, array('label' => 'DESCONTAR:', 'required' => false))

            //->add('nroPresupuesto')
            // ->add('fechaPresupuesto', 'date', array('widget' => 'single_text',
            //     'format' => 'dd-MM-yyyy', 'required' => true))
            // ->add('formaPago', 'entity', array('class' => 'ConfigBundle:FormaPago',
            //     'required' => true, 'label' => 'FORMA DE PAGO: '))
            ->add('tipo', 'hidden')
            ->add('categoriaIva', 'hidden')
            ->add('percepcionRentas', 'hidden')
            // ->add('validez',null,array('label' => 'VALIDEZ [días]:','required'=>false))
            ->add('detalles', 'collection', array(
                'type' => new PresupuestoDetalleType(),
                'by_reference' => false,
                'allow_delete' => true,
                'allow_add' => true,
                'prototype_name' => 'items',
                'attr' => array(
                    'class' => 'row item'
                )
            ))
            ->add('descuentoRecargo', null, array('attr' => array('required' => true)));
        // if ($type == 'new') {
        //     // en render de nuev presupuesto solo traer cliente por defecto
        //     $cliente = $data->getCliente()->getId();
        //     $builder->add('cliente', 'entity', array('required' => true,
        //         'class' => 'VentasBundle:Cliente', 'label' => 'DATOS DEL CLIENTE: ',
        //         'query_builder' => function (EntityRepository $repository) use ($cliente) {
        //             return $qb = $repository->createQueryBuilder('c')
        //                 ->where("c.id=" . $cliente);
        //         }
        //     ));
        // } else if ($type == 'create') {
        //     // al crear traer objeto completo para match del cliente
        //     $builder->add('cliente', 'entity', array(
        //         'class' => 'VentasBundle:Cliente',
        //         'required' => true
        //     ));
        // }
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'VentasBundle\Entity\Presupuesto',
            'cascade_validation' => true,
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'ventasbundle_presupuesto';
    }

}

src/VentasBundle/Resources/views/Presupuesto/index.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block pageheader %}
<div class="pageheader notab">
    <h1 class="pagetitle">Presupuestos / Remitos</h1>
    <span class="pagedesc">Relación con Clientes</span>
</div><!--pageheader-->
{% endblock %}
{% block contentwrapper %}
{% include "AppBundle::notificacion.html.twig" %}

<div id="contentwrapper" class="contentwrapper">
<div>
    <form id="searchform" action="{{ path('ventas_presupuesto') }}" method="get">

        {% include "VentasBundle:Partial:_partial-select2-cliente.html.twig" with { 'allowclear':true }  %}

        <div style="display: inline-block; margin-right: 30px;">
            &nbsp;&nbsp;&nbsp;
            <label><strong>Fecha Presupuesto: </strong></label>
            <input type="text" class="width100 datepicker" title="Fecha desde" value="{{desde}}" name="desde" id="desde" />
            <input type="text" class="width100 datepicker" title="Fecha hasta" value="{{hasta}}" name="hasta" id="hasta" />
            <a href="javascript:void(0)" class="editar btn btnaction btn_search" onClick="jQuery('#searchform').submit();" title="Buscar"></a>
        </div>
    </form>
</div><!-- button -->
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" id="dyntable2">
        <thead>
            <tr>
                <th style="width:100px">Nº Presupuesto</th>
                <th>Fecha</th>
                <th>Cliente</th>
                <th>Total</th>
                <th>Usuario</th>
                <th class="nosort actionbutton addbutton">
                   {% if app.user.access(app.session.get('unidneg_id'),'ventas_venta_new') %}
                    <a class="editar create" href="{{ path('ventas_presupuesto_new') }}">Nuevo Presupuesto / Remito</a>
                    {% else %} &nbsp; {% endif %}
                </th>
            </tr>
        </thead>
        <tbody>
           {% for entity in entities %}
            <tr>
                <td class="alignright">{% if entity.tipo=='R' %}<small style="float:left; font-size:8px;">REMITO</small>  {% endif %} {{entity.nroPresupuesto}} </td>
                <td><span class="hidden">{{ entity.fechaPresupuesto|date('Ymd') }}</span>{{ entity.fechaPresupuesto|date('d-m-Y') }}</td>
                <td>{{ entity.cliente }}{{ entity.nombreCliente != 'CONSUMIDOR FINAL' ? ('<br><small>' ~ entity.nombreCliente) |raw : '</small>' }}</td>
                <td class="alignright">{{ entity.montoTotal|number_format(2,',','.') }}</td>
                <td>{{entity.createdBy.username|upper }}</td>
                <td class="buttons">
                    {% if entity.estado == 'ANULADO' %}
                        <strong style="height:26px;display:block;"> ANULADO: {{ entity.updated|date('d-m-Y H:i:s') }} | {{ entity.updatedBy.username }} </strong>
                    {% else %}
                        {# SHOW #}
                        <a href="{{ path('ventas_presupuesto_show', { 'id': entity.id }) }}" class="editar btn btnaction btn_folder" title="Ver"></a>
                        {% if app.user.access(app.session.get('unidneg_id'),'ventas_presupuesto_print') %}
                        {# PRINT #}
                          <a href="#" url="{{ path('ventas_presupuesto_print', { 'id': entity.id, 'valorizado':false })}}" class="editar btn btnaction btn_print" presid="{{entity.id}}"  title="{% if entity.tipo=='P' %} Presupuesto {% else %} Remito {% endif %}"></a>
                            {% if entity.tipo=='P' %}
                                <a href="#" url="{{ path('ventas_presupuesto_print', { 'id': entity.id, 'valorizado':true })}}" class="editar btn btnaction btn_print btn_black" presid="{{entity.id}}"  title="Valorizado detallado"></a>
                            {% endif %}
                        {% endif %}

                        {% if not entity.descuentaStock and entity.estado != 'IMPRESO' %}
                        {# EDIT #}
                          <a href="{{ path('ventas_presupuesto_edit', { 'id': entity.id }) }}" class="editar btn btnaction btn_pencil" title="Editar"></a>
                        {% endif %}
                        {# REPEAT #}
                        <a href="{{ path('ventas_presupuesto_repeat', { 'id': entity.id }) }}" class="editar btn btnaction btn_refresh" title="Generar Nuevo"></a>
                        {# VENTA #}
                        <a href="{{ path('ventas_venta_presupuesto', { 'id': entity.id }) }}" class="editar btn btnaction btn_book" title="Generar Venta"></a>

                    {% endif %}
                </td>
            </tr>
           {% endfor %}
        </tbody>
    </table>
</div>
 {% endblock %}
{% block extra_javascripts %}
{% include "AppBundle::block-list-js.html.twig" %}
<script type="text/javascript">
jQuery(document).ready(function($){
    $('.datepicker').datepicker({dateFormat: 'dd-mm-yy'});

    var oTable = $('#dyntable2').dataTable();
    oTable.fnSort( [ [1,'desc'],[0,'desc'] ] );

   $('#printform').on('submit',function(){
        $('#clienteid').val($('#selectClienteIndex').val());
        $('#fdesde').val($('#desde').val());
        $('#fhasta').val($('#hasta').val());
        $('#searchterm').val( $('#dyntable2_filter input').val() );
        var datos = [];
        oTable.api().rows( { search:'applied' } ).data().each(function(value, index) {
            var i = value[1].indexOf('</span>');
            if( i >-1 ){
                var fecha = value[1].substr(i+7);
                value[1]=fecha;
            }
            value.splice(6);
            datos[index] = value;
        });
        $('#datalist').val(JSON.stringify(datos));
    });

  $('body').on('click','.btn_print', function(e){
    $(this).parent().find('.btn_pencil').remove()
  })
});
</script>
{% endblock %}

src/VentasBundle/Resources/views/Presupuesto/presupuesto-valorizado-detalle.pdf.twig
<pdf>
    <dynamic-page page-size="A4" margin-left="30px" margin-right="30px" margin-top="30px" >
        <placeholders>
            <header>
                <div height="160px" width="100%" >
                    <table font-size="11px">
                        <tr>
                            <td border.type="none" >
                                <div width="100%">
                                    <img ignore-error="true" src="{{logo}}" width="80%" />
                                </div>
                            </td>
                            <td border.color="#555555" width="50px" vertical-align="middle" text-align="center">
                                <div font-size="23px"><strong>X</strong> </div>
                            </td>
                            <td border.type="none" text-align="center" vertical-align="middle">
                                <div width="100%" font-size="16px" padding-bottom="10px">
                                    <strong> {% if (presupuesto.tipo=='P') %} PRESUPUESTO {% else %} REMITO {% endif %}</strong>
                                </div>
                                <div font-size="11px" padding-bottom="5px">
                                    <strong>Número: {{presupuesto.nroPresupuestoTxt}} </strong>
                                </div>
                                <div font-size="11px">
                                    <strong>Fecha: {{ presupuesto.fechaPresupuesto| date('d-m-Y') }} </strong>
                                    </div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" border.type="none" padding-top="20px">
                                <div padding-left="10px">
                                    <div padding-bottom="10px">{{ empresa.direccion }} </div>
                                    <div padding-bottom="5px">{{ empresa.telefono }} </div>
                                    <div padding-bottom="5px" href="mailto:{{empresa.email}}">{{ empresa.email }} </div>
                                    <div padding-bottom="10px">{{ empresa.condicionIva }} </div>
                                </div>
                            </td>
                            <td border.type="none" padding-top="10px">
                                <div padding-left="40px">
                                    <div>
                                        <div padding-bottom="10px" text-align="center"> DOCUMENTO NO VALIDO COMO FACTURA </div>
                                        <div padding-bottom="5px" text-align="right"> CUIT: {{ empresa.cuit }} </div>
                                        <div padding-bottom="5px" text-align="right"> DGR: {{ empresa.iibb }} </div>
                                        <div padding-bottom="5px" text-align="right"> Reg. Proveedores Pcia. del Chaco N° 1600-2 </div>
                                        <div padding-bottom="10px" text-align="right"> Reg. Proveedores de la Nación N° 17332-0 </div>

                                    </div>

                                </div>
                            </td>
                        </tr>

                    </table>

                    <div height="5px"></div>

                </div>
            </header>
            <footer>
                <div height="100px" width="100%">
                    <div border.color="#555555" height="1px" ></div>
                    <div font-size="7px" padding="10px"> Op: {{presupuesto.createdBy.nombre|upper}} - Ref. #{{presupuesto.nroPresupuesto}} - {{'now'|date('d-m-Y H:i')}} </div>
                </div>
            </footer>
        </placeholders>
        <div border.color="#555555" height="1px" ></div>
        <table font-size="11px">
            <tr>
                <td border.type="none" padding-top="10px">
                    <strong>CLIENTE:</strong> {{presupuesto.cliente}}
                </td>
                <td border.type="none" padding-top="10px">
                    {% if presupuesto.nombreCliente %}
                        {{presupuesto.nombreCliente}}
                    {% else %}
                        Dirección: {{presupuesto.cliente.direccion}}
                    {% endif %}
                </td>
            </tr>
            {% if not presupuesto.cliente.consumidorfinal %}
            <tr>
                <td border.type="none" padding-top="10px">
                    IVA: {{presupuesto.cliente.condicionIva.nombre|upper}}
                </td>
                <td border.type="none" padding-top="10px">
                    CUIT: {{presupuesto.cliente.cuit}}

                </td>
                <td border.type="none" padding-top="10px">
                    PROV.: {{presupuesto.cliente.provinciaRentas.shortname}}
                </td>
            </tr>
            {% endif %}
            <tr>
                <td colspan="2" border.type="none" padding-top="10px">
                    Condición de Venta: {{presupuesto.formaPago}}
                </td>
            </tr>
        </table>

        <table font-size="9px" padding-top="10px">
            <tr margin-bottom="8px">
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center" width="2 cm">
                    Código
                </td>
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center" width="2 cm">
                    Cantidad
                </td>
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center">
                    Descripción
                </td>
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center" width="2 cm">
                    Unitario
                </td>
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center" width="1.5 cm">
                    IVA
                </td>
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center" width="2 cm">
                    Total
                </td>
            </tr>
            {% for item in presupuesto.detalles %}
            <tr>
                <td border.type="none" height="15px" vertical-align="middle" text-align="center">
                    {{item.producto.codigo}}
                </td>
                <td border.type="none" height="15px" vertical-align="middle" text-align="right" padding-right="10px">
                    {{item.cantidad}} {{ item.producto.unidadmedida.nombre }}
                </td>
                <td border.type="none" height="15px" vertical-align="middle" padding-left="10px">
                    {{item.nombreProducto}}
                </td>
                <td border.type="none" height="15px" vertical-align="middle" text-align="right" padding-right="10px">
                    {% if (presupuesto.tipo=='P') %}
                        {% set precio = ( item.precioUnitarioItem+(item.precioUnitarioItem*(presupuesto.descuentoRecargo/100)) )  %}
                        {{ precio|number_format(2,',','.')}}
                    {% endif %}
                </td>
                <td border.type="none" height="15px" vertical-align="middle" text-align="right" padding-right="10px">
                    {% if (presupuesto.tipo=='P') %} {{item.alicuota|number_format(2,',','.')}} {% endif %}
                </td>
                <td border.type="none" height="15px" vertical-align="middle" text-align="right" padding-right="10px">
                    {% if (presupuesto.tipo=='P') %}  {{(precio*item.cantidad)|number_format(2,',','.')}}  {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>


        {% set cativa = (presupuesto.cliente.condicionIva) ? presupuesto.cliente.condicionIva.codigo : 'C' %}
        {% set retrentas = presupuesto.cliente.categoriaRentas ? presupuesto.cliente.categoriaRentas.retencion : 0 %}
        {% set showiva = (cativa == 'I' or cativa == 'M') %}
        {% if (presupuesto.tipo=='P') %}
         <div font-size="9px" padding-top="100px"><i> Precios y Stock sujeto a variaciones </i></div>
        <table font-size="9px" padding-top="10px">
            <tr margin-bottom="8px">
                <td border.color="#555555" background.color="#EEEEEE" height="20px" width="20%" vertical-align="middle" text-align="center">
                    Subtotal: $ {{presupuesto.subTotal|number_format(2,',','.')}}
                </td>
                <td border.color="#555555" background.color="#EEEEEE" height="20px"  vertical-align="middle" text-align="center">
                    Desc/Rec: $ {{presupuesto.totalDescuentoRecargo|number_format(2,',','.')}}
                </td>
                {% if showiva %}
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center">
                    IVA: $ {{presupuesto.totalIva|number_format(2,',','.')}}
                </td>
                {% endif %}
                {% if presupuesto.cliente.percepcionRentas > 0 %}
                <td border.color="#555555" background.color="#EEEEEE" height="20px" vertical-align="middle" text-align="center">
                    Perc.IIBB [{{presupuesto.cliente.percepcionRentas|number_format(2,'.',',')}}%]: $ {{presupuesto.totalIibb|number_format(2,',','.')}}
                </td>
                {% endif %}


                <td border.color="#555555" background.color="#EEEEEE" height="20px" width="20%" vertical-align="middle" text-align="center">
                    TOTAL: $ {{presupuesto.montoTotal|number_format(2,',','.')}}
                </td>
            </tr>
        </table>
        {% endif %}
    </dynamic-page>
</pdf>