src/VentasBundle/Entity/CajaApertura.php
<?php

namespace VentasBundle\Entity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * VentasBundle\Entity\CajaApertura
 * @ORM\Table(name="ventas_caja_apertura")
 * @ORM\Entity(repositoryClass="VentasBundle\Entity\CajaAperturaRepository")
 * @Gedmo\Loggable()
 */
class CajaApertura {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Caja", inversedBy="aperturas")
     * @ORM\JoinColumn(name="caja_id", referencedColumnName="id")
     */
    protected $caja;

    /**
     * @var date $fechaApertura
     * @ORM\Column(name="fecha_apertura", type="datetime", nullable=false)
     * @Gedmo\Versioned()
     */
    protected $fechaApertura;

    /**
     * @var integer $montoApertura
     * @ORM\Column(name="monto_apertura", type="decimal", precision=20, scale=2 )
     */
    protected $montoApertura = 0;

    /**
     * @var date $fechaCierre
     * @ORM\Column(name="fecha_cierre", type="datetime", nullable=true)
     * @Gedmo\Versioned()
     */
    protected $fechaCierre;

    /**
     * @var integer $montoCierre
     * @ORM\Column(name="monto_cierre", type="decimal", precision=20, scale=2, nullable=true )
     * @Gedmo\Versioned()
     */
    protected $montoCierre = 0;

    /**
     * @var integer $cambios
     * @ORM\Column(name="cambios", type="decimal", precision=20, scale=2, nullable=true )
     */
    protected $cambios;

    /**
     * @ORM\OneToMany(targetEntity="VentasBundle\Entity\CobroDetalle", mappedBy="cajaApertura")
     */
    protected $movimientos;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var datetime $updated
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var User $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

    /**   Diferencia encontrada entre la apertura y cierre    */
    public function getDiferencia() {
        return ($this->getMontoApertura() + $this->getTotalMovimientos()) - $this->getMontoCierre();
    }

    /** suma total de movimientos entre apertura y cierre */
    public function getTotalMovimientos() {
        $total = 0;
        // foreach($this->getIngresos() as $mov ){
        //         $total += $mov->getPago();
        // }
        // foreach($this->getGastos() as $mov ){
        //         $total -= $mov->getTotal();
        // }
        return $total;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set fechaApertura
     *
     * @param \DateTime $fechaApertura
     * @return CajaApertura
     */
    public function setFechaApertura($fechaApertura) {
        $this->fechaApertura = $fechaApertura;

        return $this;
    }

    /**
     * Get fechaApertura
     *
     * @return \DateTime
     */
    public function getFechaApertura() {
        return $this->fechaApertura;
    }

    /**
     * Set montoApertura
     *
     * @param string $montoApertura
     * @return CajaApertura
     */
    public function setMontoApertura($montoApertura) {
        $this->montoApertura = $montoApertura;

        return $this;
    }

    /**
     * Get montoApertura
     *
     * @return string
     */
    public function getMontoApertura() {
        return $this->montoApertura;
    }

    /**
     * Set fechaCierre
     *
     * @param \DateTime $fechaCierre
     * @return CajaApertura
     */
    public function setFechaCierre($fechaCierre) {
        $this->fechaCierre = $fechaCierre;

        return $this;
    }

    /**
     * Get fechaCierre
     *
     * @return \DateTime
     */
    public function getFechaCierre() {
        return $this->fechaCierre;
    }

    /**
     * Set montoCierre
     *
     * @param string $montoCierre
     * @return CajaApertura
     */
    public function setMontoCierre($montoCierre) {
        $this->montoCierre = $montoCierre;

        return $this;
    }

    /**
     * Get montoCierre
     *
     * @return string
     */
    public function getMontoCierre() {
        return $this->montoCierre;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return CajaApertura
     */
    public function setCreated($created) {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated() {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return CajaApertura
     */
    public function setUpdated($updated) {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated() {
        return $this->updated;
    }

    /**
     * Set caja
     *
     * @param \ConfigBundle\Entity\Caja $caja
     * @return CajaApertura
     */
    public function setCaja(\ConfigBundle\Entity\Caja $caja = null) {
        $this->caja = $caja;

        return $this;
    }

    /**
     * Get caja
     *
     * @return \ConfigBundle\Entity\Caja
     */
    public function getCaja() {
        return $this->caja;
    }

    /**
     * Set createdBy
     *
     * @param \ConfigBundle\Entity\Usuario $createdBy
     * @return CajaApertura
     */
    public function setCreatedBy(\ConfigBundle\Entity\Usuario $createdBy = null) {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \ConfigBundle\Entity\Usuario
     */
    public function getCreatedBy() {
        return $this->createdBy;
    }

    /**
     * Set updatedBy
     *
     * @param \ConfigBundle\Entity\Usuario $updatedBy
     * @return CajaApertura
     */
    public function setUpdatedBy(\ConfigBundle\Entity\Usuario $updatedBy = null) {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * Get updatedBy
     *
     * @return \ConfigBundle\Entity\Usuario
     */
    public function getUpdatedBy() {
        return $this->updatedBy;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->movimientos = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add movimientos
     *
     * @param \VentasBundle\Entity\CobroDetalle $movimientos
     * @return CajaApertura
     */
    public function addMovimiento(\VentasBundle\Entity\CobroDetalle $movimientos) {
        $this->movimientos[] = $movimientos;

        return $this;
    }

    /**
     * Remove movimientos
     *
     * @param \VentasBundle\Entity\CobroDetalle $movimientos
     */
    public function removeMovimiento(\VentasBundle\Entity\CobroDetalle $movimientos) {
        $this->movimientos->removeElement($movimientos);
    }

    /**
     * Get movimientos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMovimientos() {
        return $this->movimientos;
    }

    /**
     * Set cambios
     *
     * @param string $cambios
     * @return CajaApertura
     */
    public function setCambios($cambios) {
        $this->cambios = $cambios;

        return $this;
    }

    /**
     * Get cambios
     *
     * @return string
     */
    public function getCambios() {
        return $this->cambios;
    }

}

src/VentasBundle/Form/CajaAperturaType.php
<?php

namespace VentasBundle\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CajaAperturaType extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {

        $builder->add('caja')
                ->add('referer','hidden',array('mapped'=>false))
                ->add('montoApertura','hidden',array('label' => 'Monto Inicial:', 'required' => false));

    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'VentasBundle\Entity\CajaApertura'
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'ventasbundle_apertura';
    }

}

src/VentasBundle/Resources/views/CajaApertura/cierre.html.twig
{% block contentwrapper %}

<style type="text/css">
    .pagetitle.caja{
        padding-bottom:10px;
    }
    .pagetitle.fecha{
        font-size:20px;
    }
    {# #fieldmonto{
        padding:20px 0 10px 0px;
        font-size:16px;
    }
    #fieldmonto input{
        font-size:16px;
        font-weight:bold;
    } #}
</style>
<div>
    <div class="pageheader notab">
        <h1 class="pagetitle caja aligncenter">
            {{entity.caja.nombre}}
        </h1>
        <h1 class="pagetitle fecha aligncenter">
            {{entity.fechaCierre|date('d/m/Y')}}
            <span class="js-hora"> {{entity.fechaCierre|date('H:i:s')}}</span>
        </h1>
    </div>

    {{ form_start(form, {'attr': {'class': 'stdform','id':'ventasbundle_cierre'}}) }}

    <fieldset id="fieldmonto">
        {{ form_row(form.montoCierre, { 'attr': {'class' : 'width100 number'} })}}
    </fieldset>
    <input type="hidden" name="id" value="{{ entity.id }}"/>
    <p class="actionBar aligncenter hidden">
        <button class="js-registrar-cierre" type="button" >Registrar Cierre de Caja</button>
    </p>

    <div name="rest" class="hiddenformrest"> {{ form_rest(form) }} </div>
    {{ form_end(form) }}

</div>

{% endblock %}

src/VentasBundle/Resources/views/CajaApertura/index.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block pageheader %}
<div class="pageheader notab">
        <h1 class="pagetitle">Apertura / Cierre de Caja</h1>
        <span class="pagedesc">Listado de Aperturas y Cierres de Cajas</span>
</div><!--pageheader-->
{% endblock %}
{% block contentwrapper %}
    {% include "AppBundle::notificacion.html.twig" %}

<div id="contentwrapper" class="contentwrapper">
{# fomulario para filtros #}
    <form id="searchform" action="{{ path('ventas_apertura') }}" method="get" style="margin-bottom:10px">
        <div style="display: inline-block; margin-bottom: 10px;">
            &nbsp;&nbsp;&nbsp;
            <label><strong>Caja:</strong></label>
            <select class="uniformselect" id="selectCaja" name="cajaId">
            {% for cj in cajas %}
                <option value="{{cj.id}}" {% if cj.id==cajaId %} selected="selected" {% endif %}>
                  {{cj.nombre}} - {{ cj.descripcion }}
                </option>
            {% endfor %}
            </select>
        </div>
        <div style="display: inline-block; margin-right: 30px;">
            &nbsp;&nbsp;&nbsp;
            <label><strong>Fecha: </strong></label>
            <input type="text" class="width100 datepicker" title="Fecha desde" value="{{desde}}" name="desde" id="desde" />
            <input type="text" class="width100 datepicker" title="Fecha hasta" value="{{hasta}}" name="hasta" id="hasta" />
            <a href="javascript:void(0)" class="editar btn btnaction btn_search" onClick="jQuery('#searchform').submit();" title="Buscar"></a>
        </div>
<!-- Botones para cierres X y Z -->
{% if app.session.get('caja') and app.session.get('caja')['id'] == caja.id %}
        <div style="display: inline-block;float:right;" >
            <label><strong>TICKEADORA FISCAL: </strong></label>
            <button type="button" class="stdbtn btn_orange" onclick="cierreX()" style="padding:7px 20px">
                Cierre X <img class="loader_cmCierreX hidden" src={{ asset('assets/images/loaders/loader8.gif') }}>
            </button>
            <button type="button" class="stdbtn btn_red" onclick="cierreZ()" style="padding:7px 20px">
                Cierre Z <img class="loader_cmCierreZ hidden" src={{ asset('assets/images/loaders/loader8.gif') }}>
            </button>
            <button type="button" class="stdbtn btn_grey" onclick="test()" style="display:none;padding:7px 20px">
                Test <img class="loader_cmObtenerDatosDeInicializacion hidden" src={{ asset('assets/images/loaders/loader8.gif') }}>
            </button>
            <button type="button" class="stdbtn btn_grey" onclick="reporteSemanal()" style="padding:7px 20px">
                Reporte Semanal <img class="loader_cmObtenerPrimerBloqueReporteElectronico hidden" src={{ asset('assets/images/loaders/loader8.gif') }}>
            </button>
        </div>
{% endif %}
    </form>

{# Banner con estado de la caja #}
{% if app.session.get('caja') and app.session.get('caja')['id'] == caja.id %}
    {% if app.session.get('caja')['apertura'] %}
        {% set msg, txt = 'msgsuccess', app.session.get('caja')['nombre'] ~ ' ABIERTA' %}
        {% set btn = '<button title="Realizar el Cierre de Caja" class="js-cierre stdbtn btn_black floatright" > Cierre de Caja </button>'  %}
    {% else %}
        {% set msg, txt = 'msgerror', app.session.get('caja')['nombre'] ~ ' CERRADA' %}
        {% set btn = '<button title="Realizar la Apertura de Caja" class="js-apertura stdbtn btn_black floatright" > Apertura de Caja </button>'  %}
    {% endif %}
<div class="notibar {{msg}}">
    <p>
        <strong> {{txt}} </strong> {{ btn|raw }}
    </p>
</div>
{% endif %}

    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" id="ccaja_apertura_table">
        <thead>
            <tr>
                <th class="nosort">#</th>
                <th class="nosort">Apertura</th>
                <th class="nosort hidden">Monto</th>
                <th class="nosort">Usuario</th>
                <th class="nosort" style="background:#868686;padding:1px;"></th>
                <th class="nosort">Cierre</th>
                <th class="nosort">Monto</th>
                <th class="nosort">Usuario</th>
                <th class="hidden nosort">DIFERENCIA</th>
                <th class="nosort" style="width:10%"></th>
            </tr>
        </thead>
        <tbody>
            {% for apertura in entities|reverse %}
                {% if loop.index<40 %}
                    <tr>
                        <td>{{ apertura.id }}</td>
                        <td>{{ apertura.fechaApertura|date('d-m-Y H:i') }}</td>
                        <td class="hidden">{{ apertura.montoApertura|number_format(2,',','.') }}</td>
                        <td>{{ apertura.createdBy.username|upper }}</td>
                        <td style="background:#868686;padding:1px;"></td>
                        <td>{% if apertura.fechaCierre %}
                                    {{apertura.fechaCierre|date('d-m-Y H:i')}}
                            {% elseif app.user.isAdmin(app.session.get('unidneg_id')) %}
                                <a target="_blank" title="Movimientos" href="{{ path('ventas_apertura_arqueo',{'id':apertura.id}) }}" class="hidden arqueo-caja anchorbutton"> Movimientos </a>
                            {% endif %}
                        </td>
                        <td>{% if apertura.fechaCierre  %}{{apertura.montoCierre|number_format(2,',','.')}}{% endif %}</td>
                        <td>{% if apertura.fechaCierre %}{{ apertura.updatedBy.username }}{% endif %}</td>
                        <td class="hidden {% if apertura.diferencia<0 %} rojo {% endif %}" >{% if apertura.fechaCierre %}{{apertura.diferencia|number_format(2,',','.')}}{% endif %}</td>
                        <td>
{#                        {% if apertura.fechaCierre %}#}
                          {% if  apertura.movimientos|length == 0  %}
                              <span style="font-size:8px"> SIN MOVIMIENTOS </span>
                          {% else %}
                              <a target="_blank" href="{{ path('ventas_apertura_arqueo',{'id':apertura.id}) }}" title="Ver informe de Cierre" class="btn btnaction btn_folder"> <i class="icon-file"></i></a>
                          {% endif %}
{#                        {% endif %}#}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}
{% block extra_javascripts %}
{% include "AppBundle::block-list-js.html.twig" %}
<script type="text/javascript" src="{{ asset('assets/js/custom/ifu.js') }}"></script>
<script type="text/javascript">

jQuery(document).ready(function($){
    $('#selectCaja').change(function(){
        $('#searchform').submit();
    });
    $('.datepicker').datepicker({dateFormat: 'dd-mm-yy'});

    $('.js-apertura').on('click', function(){
        //caja_id = $('#selectCaja').val();  id de caja
        url = '{{ path("ventas_apertura_new")}}'; // url del partial a cargar en modal
        aperturaCajaVentas(url, false)
    });
    $('.js-cierre').on('click', function(){
        //caja_id = $('#selectCaja').val();  id de caja
        url = '{{ path("ventas_cierre_new")}}'; // url del partial a cargar en modal
        cierreCajaVentas(url)
    });
});
// cierres de tickeadora fiscal
function cierreX(){
    const comando = 'cmCierreX'
    setFacturando(true,comando)
    setTimeout(function(){
        const driver = getDriver()
        try {
            driver.iniciarTrabajo();
            driver.cierreX();
            driver.finalizarTrabajo();
            registrarMovimientoIfu(comando,driver.response)
        } catch (e){
            registrarMovimientoIfu(comando,'','',e)
            alert('ERROR: '+e);
            setFacturando(false,comando)
        }
    }, 1000);
}

function cierreZ(){
    const comando = 'cmCierreZ'
    setFacturando(true,comando)
    setTimeout(function(){
        const driver = getDriver()
        try {
            driver.iniciarTrabajo();
            driver.cierreZ();
            driver.finalizarTrabajo();
            registrarMovimientoIfu(comando,driver.response)
        } catch (e){
            registrarMovimientoIfu(comando,'','',e)
            alert('ERROR: '+e);
            setFacturando(false,comando)
        }
    }, 1000);
}

function test(){
    const comando = 'cmObtenerDatosDeInicializacion'
    setFacturando(true,comando)
    setTimeout(function(){
{#        const driver = getDriver()#}
        try {
            {#driver.iniciarTrabajo();
            driver.obtenerDatosDeInicializacion();
            driver.finalizarTrabajo();
            const result = driver.response#}
            registrarMovimientoIfu(comando,'')

        } catch (e){
            alert(e);
            setFacturando(false,comando)
        }
    }, 1000);
}

function reporteSemanal(){
    const comando = 'cmObtenerPrimerBloqueReporteElectronico'
    setFacturando(true,comando)
    const url = "{{ path('get_datos_reporte_semanal') }}"
    msg = 'Ha ocurrido un error obteniendo los datos para el reporte'
    jQuery.getJSON( url , {'id': "{{caja.id}}"}).done(function(data){
        jReporteSemanal('Seleccionar Período:(ddmmaa)', data, 'Reporte Semanal', function(res) {
            if(res){
                data.desde = res.desde.trim()
                data.hasta = res.hasta.trim()
                const file = data.path+'ReporteSemanal_'+data.desde+'_al_'+data.hasta+'.zip'
                if(data.desde  && data.hasta){
                    const driver = getDriver()
                    try {
                        driver.iniciarTrabajo();
                        const trfecha = 0
                        const resp = driver.obtenerPrimerBloqueReporteElectronico(data.desde,data.hasta,file,trfecha)
                        if( resp ){
                            do{
                                resp = driver.obtenerSiguienteBloqueReporteElectronico()
                            }while(resp)
                        }
                        driver.finalizarTrabajo();
                        const result = driver.response ? driver.response : 'OK'
                        registrarMovimientoIfu(comando,result,data)
                    } catch (e){
                        registrarMovimientoIfu(comando,'',data,e)
                        alert('ERROR: '+e);
                        setFacturando(false,comando)
                    }
                }
            }
        });
    }).fail(function(data){
        alert(msg)
      }).always(function(){
          setFacturando(false)
      })
}

function getDriver(){
  modelo = '{{modelo_tickeadora}}'
  puerto = '{{puerto_tickeadora}}'
  baudios = '{{baudios_tickeadora}}'
  host = '{{host_tickeadora}}'
  // verificar si falta configuracion
  if( !modelo || !puerto || !baudios || !host ){
    alert( ' No se pueden acceder a la impresora en este momento. Faltan configuraciones!');
    setFacturando(false)
    return false
  }
  const driver = new Driver();
  driver.host = host
  driver.modelo = modelo;
  driver.puerto = puerto;
  driver.baudios = baudios;
  return driver
}

function setFacturando(on,action=''){
  if(on){
     jQuery('.loader_'+action).removeClass('hidden')
  }else{
     jQuery('[class^="loader_"]').addClass('hidden');
  }
}

function registrarMovimientoIfu(comando, result, fechas=null, error=null){
   url = "{{ path('ifu_registrar_movimiento') }}"
   data = { comando, result, fechas, error }
   jQuery.post(url, data, function(data){
    if(data.res === 'OK'){
        switch (comando) {
            case 'cmCierreZ':
            case 'cmCierreX':
              const cierre = result.cierreZTotales.nroCierre
              message = 'Cierre finalizado! Numero: '+ cierre
              break;
            case 'cmObtenerDatosDeInicializacion':
              const nroSerie = result.nroSerie
              message = 'Datos obtenidos... Nro Serie: '+ nroSerie
              break;
            case 'cmObtenerPrimerBloqueReporteElectronico':
              message = 'Reporte Semanal'
              break;
            default:
              message = null
          }
        if(!error) alert(message)
    }else{
      alert(data.msg)
    }
    setFacturando(false)
  },'json').fail(function(data){
    alert('Ha ocurrido un error')
  }).always(function(){
      setFacturando(false)
  })
}

</script>
{% endblock %}

src/VentasBundle/Resources/views/CajaApertura/unificado.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block pageheader %}
<div class="pageheader notab">
        <h1 class="pagetitle">Informes de Caja</h1>
        <span class="pagedesc">Listado de Unificado de Cajas</span>
</div><!--pageheader-->
{% endblock %}
{% block contentwrapper %}
    {% include "AppBundle::notificacion.html.twig" %}

<div id="contentwrapper" class="contentwrapper">
{# fomulario para filtros #}
    <form id="searchform" action="{{ path('ventas_apertura_unificado') }}" method="get" style="margin-bottom:10px">
        <div style="display: inline-block; margin-right: 30px;">
            &nbsp;&nbsp;&nbsp;
            <label><strong>Fecha: </strong></label>
            <input type="text" class="width100 datepicker" title="Fecha desde" value="{{desde}}" name="desde" id="desde" />
            <input type="text" class="width100 datepicker" title="Fecha hasta" value="{{hasta}}" name="hasta" id="hasta" />
            <a href="javascript:void(0)" class="editar btn btnaction btn_search" onClick="jQuery('#searchform').submit();" title="Buscar"></a>
        </div>
    </form>
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" id="ccaja_apertura_table">
        <thead>
            <tr>
                <th class="nosort">#</th>
                <th class="nosort">CAJA</th>
                <th class="nosort">Apertura</th>
                <th class="nosort hidden">Monto</th>
                <th class="nosort">Usuario</th>
                <th class="nosort" style="background:#868686;padding:1px;"></th>
                <th class="nosort">Cierre</th>
                <th class="nosort">Monto</th>
                <th class="nosort">Usuario</th>
                <th class="hidden nosort">DIFERENCIA</th>
                <th class="nosort" style="width:10%"></th>
            </tr>
        </thead>
        <tbody>
            {% for dia in dias %}
                <tr style="height: 40px">
                    <th colspan="8" style="text-align: left; padding-left: 20px; border-left: 1px solid #ddd;">
                        {{ dia|date('d-m-Y') }}
                    </th>
                    <th style="border-right: 1px solid #ddd">
                         <a target="_blank" href="{{ path('ventas_arqueo_unificado',{'fecha':dia}) }}" title="Ver Reporte Unificado" class="stdbtn btn_grey">Unificado</a>
                    </th>
                </tr>
            {% for apertura in entities if apertura.fechaApertura|date('d-m-Y') == dia|date('d-m-Y') %}
                {% if loop.index<40 %}
                    <tr>
                        <td>{{ apertura.id }}</td>
                        <td>{{ apertura.caja.nombre }}</td>
                        <td>{{ apertura.fechaApertura|date('d-m-Y H:i') }}</td>
                        <td class="hidden">{{ apertura.montoApertura|number_format(2,',','.') }}</td>
                        <td>{{ apertura.createdBy.username|upper }}</td>
                        <td style="background:#868686;padding:1px;"></td>
                        <td>{% if apertura.fechaCierre %}
                                    {{apertura.fechaCierre|date('d-m-Y H:i')}}
                            {% elseif app.user.isAdmin(app.session.get('unidneg_id')) %}
                                <a target="_blank" title="Movimientos" href="{{ path('ventas_apertura_arqueo',{'id':apertura.id}) }}" class="hidden arqueo-caja anchorbutton"> Movimientos </a>
                            {% endif %}
                        </td>
                        <td>{% if apertura.fechaCierre  %}{{apertura.montoCierre|number_format(2,',','.')}}{% endif %}</td>
                        <td>{% if apertura.fechaCierre %}{{ apertura.updatedBy.username }}{% endif %}</td>
                        <td class="hidden {% if apertura.diferencia<0 %} rojo {% endif %}" >{% if apertura.fechaCierre %}{{apertura.diferencia|number_format(2,',','.')}}{% endif %}</td>
                        <td style="text-align:center">
                          {% if  apertura.movimientos|length == 0  %}
                              <span style="font-size:8px"> SIN MOVIMIENTOS </span>
                          {% else %}
                              <a target="_blank" href="{{ path('ventas_apertura_arqueo',{'id':apertura.id}) }}" title="Ver informe de Cierre" class="btn btnaction btn_folder"> </a>
                          {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
           {% endfor  %}
        </tbody>
    </table>
</div>

{% endblock %}
{% block extra_javascripts %}
{% include "AppBundle::block-list-js.html.twig" %}
<script type="text/javascript" src="{{ asset('assets/js/custom/ifu.js') }}"></script>
<script type="text/javascript">
jQuery(document).ready(function($){
    $('.datepicker').datepicker({dateFormat: 'dd-mm-yy'});
});
</script>
{% endblock %}